name: Release when bump version in package.json

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nyaa8/package-version@v1
      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: v${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: v${{ env.PACKAGE_VERSION }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.checkTag.outputs.exists == 'false'

      - name: Update major version and latest tag # for GitHub Actions, see https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning
        run: |
          major=$(echo v"$PACKAGE_VERSION" | sed -r 's/(v[0-9]+).*/\1/')
          git tag "$major"
          git tag latest
          git push --tags --force
        if: steps.checkTag.outputs.exists == 'false'

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,job,took
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.checkTag.outputs.exists == 'false'
