name: Update draft release

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all
jobs:
  release-drafter:
    runs-on: ubuntu-latest

    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@main
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
