name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: version
        with:
          prefix: v
      - name: valid version only step
        run: echo Found valid version format in tag!
        if: steps.version.outputs.is_valid == 'true'
      - name: Stable version only step
        run: echo Found stable version in tag!
        if: steps.version.outputs.is_stable == 'true'
