name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: version
      with: 
        prefix: v
    - name: valid version only step
      run: echo Found valid version format in tag!
      if: steps.version.outputs.is_valid == 'true'
    - name: Stable version only step
      run: echo Found stable version in tag!
      if: steps.version.outputs.is_stable == 'true'